package com.foodprocurement.web;
import com.foodprocurement.domain.Entities.*; import com.foodprocurement.repository.Repositories.*; import io.swagger.v3.oas.annotations.Operation; import jakarta.validation.Valid; import java.math.BigDecimal; import java.util.*; import org.springframework.data.jpa.repository.JpaRepository; import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/v1") public class ApiController {
 private final Standards standards; private final Suppliers suppliers; private final Plans plans; private final Inquiries inquiries; private final Bids bids; private final Orders orders; private final Deliveries deliveries; private final Inspections inspections; private final Lots lots; private final Settlements settlements;
 ApiController(Standards standards,Suppliers suppliers,Plans plans,Inquiries inquiries,Bids bids,Orders orders,Deliveries deliveries,Inspections inspections,Lots lots,Settlements settlements){this.standards=standards;this.suppliers=suppliers;this.plans=plans;this.inquiries=inquiries;this.bids=bids;this.orders=orders;this.deliveries=deliveries;this.inspections=inspections;this.lots=lots;this.settlements=settlements;}
 @GetMapping("/standards") public List<FoodStandard> standards(){return standards.findAll();} @PostMapping("/standards") @ResponseStatus(HttpStatus.CREATED) public FoodStandard createStandard(@RequestBody FoodStandard x){return standards.save(x);}
 @GetMapping("/suppliers") public List<Supplier> suppliers(){return suppliers.findAll();} @PostMapping("/suppliers") @ResponseStatus(HttpStatus.CREATED) public Supplier createSupplier(@RequestBody Supplier x){return suppliers.save(x);}
 @GetMapping("/plans") public List<ProcurementPlan> plans(){return plans.findAll();} @PostMapping("/plans") @ResponseStatus(HttpStatus.CREATED) public ProcurementPlan createPlan(@RequestBody ProcurementPlan x){return plans.save(x);}
 @GetMapping("/inquiries") public List<Inquiry> inquiries(){return inquiries.findAll();} @PostMapping("/inquiries") @ResponseStatus(HttpStatus.CREATED) public Inquiry createInquiry(@RequestBody Inquiry x){return inquiries.save(x);}
 @Operation(summary="供应商报价；同一供应商可重复提交，以最新报价为准") @GetMapping("/inquiries/{id}/bids") public List<Bid> bids(@PathVariable UUID id){return bids.findByInquiryIdOrderByAmountAsc(id);} @PostMapping("/inquiries/{id}/bids") @ResponseStatus(HttpStatus.CREATED) public Bid bid(@PathVariable UUID id,@RequestBody Bid x){x.inquiryId=id; return bids.save(x);}
 @GetMapping("/orders") public List<PurchaseOrder> orders(){return orders.findAll();} @PostMapping("/orders") @ResponseStatus(HttpStatus.CREATED) public PurchaseOrder createOrder(@RequestBody PurchaseOrder x){return orders.save(x);}
 @GetMapping("/deliveries") public List<Delivery> deliveries(){return deliveries.findAll();} @PostMapping("/deliveries") @ResponseStatus(HttpStatus.CREATED) public Delivery createDelivery(@RequestBody Delivery x){return deliveries.save(x);}
 @GetMapping("/inspections") public List<Inspection> inspections(){return inspections.findAll();} @PostMapping("/inspections") @ResponseStatus(HttpStatus.CREATED) public Inspection createInspection(@RequestBody Inspection x){return inspections.save(x);}
 @GetMapping("/inventory") public List<InventoryLot> inventory(){return lots.findAll();} @PostMapping("/inventory") @ResponseStatus(HttpStatus.CREATED) public InventoryLot createLot(@RequestBody InventoryLot x){return lots.save(x);}
 @GetMapping("/settlements") public List<Settlement> settlements(){return settlements.findAll();} @PostMapping("/settlements") @ResponseStatus(HttpStatus.CREATED) public Settlement createSettlement(@RequestBody Settlement x){return settlements.save(x);}
 @Operation(summary="以库存批次号追溯食材来源") @GetMapping("/traceability/{lotNo}") public Map<String,Object> trace(@PathVariable String lotNo){var lot=lots.findByLotNo(lotNo).stream().findFirst().orElseThrow(()->new NoSuchElementException("未找到批次")); return Map.of("lot",lot,"standard",standards.findById(lot.standardId).orElse(null),"supplier",suppliers.findById(lot.supplierId).orElse(null));}
 @GetMapping("/dashboard") public Map<String,Object> dashboard(){return Map.of("standards",standards.count(),"suppliers",suppliers.count(),"plans",plans.count(),"openInquiries",inquiries.findAll().stream().filter(x->"OPEN".equals(x.status)).count(),"orders",orders.count(),"inventoryLots",lots.count(),"pendingSettlements",settlements.findAll().stream().filter(x->!"PAID".equals(x.status)).count());}
 @ExceptionHandler(NoSuchElementException.class) ResponseEntity<Map<String,String>> missing(NoSuchElementException e){return ResponseEntity.status(404).body(Map.of("message",e.getMessage()));}
}
